name: simple_eye_dropper_example
description: Demonstrates how to use the simple_eye_dropper plugin.

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  simple_eye_dropper:
    path: ../

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
