name: simple_eye_dropper
description: A simple eye dropper widget.
version: 0.1.0
homepage: https://github.com/satoshiiorg/simple_eye_dropper

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.satoshii.simple_eye_dropper
        pluginClass: SimpleEyeDropperPlugin
      ios:
        pluginClass: SimpleEyeDropperPlugin
  # For widget test
  assets:
    - test/music_castanet_girl.png
